apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: argocd
spec:
  type: NodePort
  selector:
    app: mlops-app   # ðŸ”¥ MUST MATCH POD LABEL
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32415
